version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    logging:
      driver: none
    restart: always
    ports:
      - 27017:27017
  api:
    container_name: auth-microservice-container
    build: .
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/authDb
    ports:
      - 5050:5050
    depends_on:
      - mongo
    links:
      - mongo